### PR TITLE
Use direct import to react-router.

### LINKED ISSUE #5079: Bundle size is bigger than necessary due to ES6 imports
I am using react-router-dom and webpack 2 and it seems the tree shaking does not work well enough to remove unused modules.

I managed to fix it locally by changing the import style from

```
import { Router } from 'react-router' 
```
to

```
import Router from 'react-router/Router' 
```
everywhere.

## Version
4.0.0

Is this something that would be interesting to do a PR on?

### PR DESCRIPTION
**Pull request by ruiaraujo**
Fix #5079.

### CODE REVIEW

File: packages/react-router-dom/modules/Router.js [hunk 1]
```diff
@@ -1 +1 @@
-export { Router as default } from 'react-router'
+export { default } from 'react-router/Router'
```
Comment (timdorr) [inline packages/react-router-dom/modules/Router.js]: (Just picking one of these at random, but this applies to all the re-exports).

Unfortunately, in the packaged form, the ES module versions of these files actually live in `/es/`. So to get tree shaking benefits beyond these exports, you would actually have to link to `react-router/es/Router`. But that would break non-ES-aware bundlers. 

I'm not sure if there's a good option here. If you import directly from `react-router/es/Router`, that is the best way to get tree-shaking benefits. Perhaps we should remove the re-exports entirely?

Comment (ruiaraujo) [inline packages/react-router-dom/modules/Router.js]: Removing  re-exports would be a major change so maybe it is a bit drastic.

Also what tree shaking benefits would you hope to get that direct imports to not give you?

Since react-router mainly exports a single module from each file, tree shaking actually does not provide any value beyond removing unused modules/file which we achieve here through direct imports.

Linking to the CommonJS build by default is just the safer option but actually I think I can improve this.

Comment (ruiaraujo) [inline packages/react-router-dom/modules/Router.js]: Actually to improve on this, my initial idea was a bit of overkill.

I was thinking of a custom Babel plugin that will rewrite the export to right direct import depending on the build. I personally feel that the gain will be very small but I am available to do this just for the fun of it.

@timdorr what do you think? Custom babel plugin seems too much?

So I decided to go the lazy route. Check it out.

**Comment by ruiaraujo** [comment]
@timdorr Any chance of taking a look at this again?

**Comment by timdorr** [comment]
Yeah, I will soon, but I have limited time available for the rest of the month. Big product release (2 years of work!) is coming up on the 30th and I need to focus on that.

**Comment by ruiaraujo** [comment]
Good luck then! :crossed_fingers:

**Comment by ruiaraujo** [comment]
@timdorr Hope your release went fine. Any time available to take a look at this?

**Comment by mjackson** [comment]
Just to be clear, @ruiaraujo, this change is for people who are using `babel-plugin-transform-imports` with the router, right? Is that plugin not able to understand the `export { Something as default } from '...'` yet?

**Comment by mjackson** [comment]
Also, isn't this the kind of thing that tree-shaking was designed to help out with?

**Comment by timdorr** [comment]
> Just to be clear, @ruiaraujo, this change is for people who are using babel-plugin-transform-imports with the router, right?

Nope, this is for webpack 2/3 support for ES modules. The direct re-exporting (`export { Router as default } from 'react-router'`) is apparently not tree-shake-able by webpack. This will reduce bundle sizes significantly for those that are using the es build with webpack 2/3.

**Comment by timdorr** [comment]
BTW, this is basically our exact issue: https://github.com/webpack/webpack/issues/2867#issuecomment-247288543 It re-exports from a file, not a npm module, but it's the same basic issue.

**Comment by mjackson** [comment]
Seems like a webpack bug, not ours.

**Comment by timdorr** [comment]
More like a misunderstand of what webpack means by "tree shaking". It's different from Rollup's. Hopefully the module concatenation stuff helps it out too, since it's somewhat related.

**Comment by mjackson** [comment]
So you're saying there's a blessed way to declare your imports if you want to take advantage of webpack's tree shaking? Because if you declare it like `export { Something as default } from '...'` webpack doesn't understand that?

**Comment by ruiaraujo** [comment]
With this import style we do not rely on tree shaking at all because the dependency is declared directly.
It does not affect consumers at all besides the fact they get smaller bundles compared to before.

**Comment by mjackson** [comment]
@ruiaraujo What do you mean by "the dependency is declared directly"? Can you please be a little more specific?

**Comment by ruiaraujo** [comment]
@mjackson If this PR is merged,  react-router-dom will import MemoryRouter from react-router in practice as
```import MemoryRouter from 'react-router/es/MemoryRouter'``` instead of
```import {MemoryRouter} from 'react-router'```

So this is what I mean by a directly imported dependency. Sorry for not being more explicit before.

**Comment by mjackson** [comment]
Ah, so we're using our own poor-man's tree shaking so webpack doesn't have to implement it for real? Bah. That's lame.

**Comment by ruiaraujo** [comment]
Apologies for being pragmatic in my approach. ;)

**Comment by mjackson** [comment]
Oh, I don't blame you @ruiaraujo ;) I think we can probably go ahead and merge this for now. Thanks for the PR.

**Comment by ruiaraujo** [comment]
I have rebased and fixed the conflicts.

**Comment by umidbekkarimov** [comment]
Take a look to [babel-plugin-direct-import](https://github.com/umidbekkarimov/babel-plugin-direct-import), it works with [RR3](https://github.com/ReactTraining/react-router/tree/v3) and [RR4](https://github.com/umidbekkarimov/babel-plugin-direct-import#react-router-4).

**Comment by timdorr** [comment]
Thanks, @ruiaraujo. Based on Michael's comments, it looks like we're good to go here.
